[IAQSensor]
row = 10
columns = 10
defaultLevel = "MODERATE"
timeUnit = "SECONDS"

[[IAQSensor.cell]]
    cellNumber = 62
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 63
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 63
    level = "POOR"
    fromTime = 120

[[IAQSensor.cell]]
    cellNumber = 12
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 13
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 13
    level = "POOR"
    fromTime = 120

[[IAQSensor.cell]]
    cellNumber = 2
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 3
    level = "MODERATE"
    fromTime = 0
[[IAQSensor.cell]]
    cellNumber = 3
    level = "POOR"
    fromTime = 120
