package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import iot.Parameters;
import iot.SimulationRunner;

import javax.swing.*;
import java.awt.*;


public class editParameters {
    private Parameters parameters;
    private SimulationRunner simulationRunner;
    private JTabbedPane tabbedPane1;
    private JPanel mainPanel;
    private JButton classSaveButton;
    private JButton updateMoteButton;
    private JSpinner bufferProbHeightSpinner;
    private JSpinner pathProbSpinner;
    private JSpinner synchronisationSpinner;
    private JSpinner runs;
    private JSpinner calculateFirstSpinner;
    private JSpinner removeConn;
    private JLabel removeVisitedConnectionsLabel;
    private JSpinner analysingMethod;
    private JSpinner bufferProbWidthSpinner;

    public editParameters(Parameters parameters, SimulationRunner simulationRunner) {
        this.parameters = parameters;
        this.simulationRunner = simulationRunner;
        refresh();


        classSaveButton.addActionListener(e -> {
            parameters.setBetterpath((Double) pathProbSpinner.getValue());
            parameters.setBufferSizeHeight((Integer) bufferProbHeightSpinner.getValue());
            parameters.setBuffersizeWidth((Integer) bufferProbWidthSpinner.getValue());
            parameters.setSynchronisation((Integer) synchronisationSpinner.getValue());
            parameters.setAmountRuns((Integer) runs.getValue());
            parameters.setSetupFirst((Integer) calculateFirstSpinner.getValue());
            parameters.setRemoveConn((Integer) removeConn.getValue());
            parameters.setAnalysingMethod((Integer) analysingMethod.getValue());
            refresh();
            parameters.updateFile(simulationRunner.getParameterFile());
        });

        updateMoteButton.addActionListener(e -> {
            parameters.setBetterpath((Double) pathProbSpinner.getValue());
            parameters.setBufferSizeHeight((Integer) bufferProbHeightSpinner.getValue());
            parameters.setBuffersizeWidth((Integer) bufferProbWidthSpinner.getValue());
            parameters.setSynchronisation((Integer) synchronisationSpinner.getValue());
            parameters.setAmountRuns((Integer) runs.getValue());
            parameters.setSetupFirst((Integer) calculateFirstSpinner.getValue());
            parameters.setRemoveConn((Integer) removeConn.getValue());
            parameters.setAnalysingMethod((Integer) analysingMethod.getValue());
            refresh();
        });

    }

    private void refresh() {
        bufferProbHeightSpinner.setModel(new SpinnerNumberModel(parameters.getBuffersizeHeight(), 1, Integer.MAX_VALUE, 1));
        bufferProbWidthSpinner.setModel(new SpinnerNumberModel(parameters.getBuffersizeWidth(), 1, Integer.MAX_VALUE, 1));
        synchronisationSpinner.setModel(new SpinnerNumberModel(parameters.getSynchronisation(), 0, 1, 1));
        calculateFirstSpinner.setModel(new SpinnerNumberModel(parameters.getSetupFirst(), 0, 2, 1));
        runs.setModel(new SpinnerNumberModel(parameters.getAmountRuns(), 1, Integer.MAX_VALUE, 1));
        pathProbSpinner.setModel(new SpinnerNumberModel(parameters.getBetterpath(), 0.001, 1, 0.001));
        removeConn.setModel(new SpinnerNumberModel(parameters.getRemoveConn(), 0, 1, 1));
        analysingMethod.setModel(new SpinnerNumberModel(parameters.getAnalysingMethod(), 0, 2, 1));
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setMinimumSize(new Dimension(750, 400));
        mainPanel.setPreferredSize(new Dimension(750, 400));
        tabbedPane1 = new JTabbedPane();
        tabbedPane1.setEnabled(true);
        mainPanel.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(4, 5, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Parameters", panel1);
        updateMoteButton = new JButton();
        updateMoteButton.setText("Update");
        panel1.add(updateMoteButton, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        classSaveButton = new JButton();
        classSaveButton.setText("Save");
        panel1.add(classSaveButton, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Without Network");
        panel1.add(label1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        calculateFirstSpinner = new JSpinner();
        panel1.add(calculateFirstSpinner, new GridConstraints(0, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Synchronisation Issue");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        synchronisationSpinner = new JSpinner();
        panel1.add(synchronisationSpinner, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Amount Runs");
        panel1.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        runs = new JSpinner();
        panel1.add(runs, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeConn = new JSpinner();
        panel1.add(removeConn, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pathProbSpinner = new JSpinner();
        panel1.add(pathProbSpinner, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Better path");
        panel1.add(label4, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Remove connections");
        panel1.add(label5, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Buffer size (width)");
        panel1.add(label6, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        bufferProbHeightSpinner = new JSpinner();
        panel1.add(bufferProbHeightSpinner, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(103, 28), null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Analysing Method");
        panel1.add(label7, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label8 = new JLabel();
        label8.setText("Buffer size (height)");
        panel1.add(label8, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(119, 28), null, 0, false));
        analysingMethod = new JSpinner();
        panel1.add(analysingMethod, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        bufferProbWidthSpinner = new JSpinner();
        panel1.add(bufferProbWidthSpinner, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(103, 28), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}

